[package]
authors = ["Anıl Tuncel <anil.tuncel@alumni.ethz.ch>"]
categories = ["science", "visualization", "science::neuroscience"]
description = "Neurodata Without Borders viewer"
name = "nwbview"
version = "0.2.5"
edition = "2021"
repository = "https://github.com/brainhack-ch/nwbview"
license = "Apache-2.0"
readme = "README.md"
keywords = ["neuroscience", "viewer", "visualization", "NWB", "GUI"]

include = [
  "Cargo.lock",
  "Cargo.toml",
  "LICENSE",
  "src/**/*",
  "static/icon.png",
]

[[bin]]
name = "nwbview"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.0"
rfd = "0.11"
hdf5 = { package = "hdf5-metno", version = "0.14.1" }
egui_extras = "0.21.0"
image = "0.24.5"
